---
- name: Install software on a new Ubuntu system
  hosts: localhost
  become: yes
  tasks:
    # Update and upgrade system packages
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist

    # Install essential packages
    - name: Install required packages
      apt:
        name:
          - zsh
          - tmux
          - vim
          - neovim
          - cmake
          - gcc
          - stow
          - neofetch
          - ripgrep
          - xclip
          - vlc
          - curl
          - git
          - unzip
          - gnupg
          - build-essential
          - eza
          - gnome-shell-extension-manager
          - pipx
        state: present

    # Install Zsh plugins
    - name: Clone Zsh plugins
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        update: yes
      loop:
        - {
            repo: "https://github.com/zsh-users/zsh-autosuggestions",
            dest: "{{ ansible_env.HOME }}/.zsh/zsh-autosuggestions",
          }
        - {
            repo: "https://github.com/zsh-users/zsh-syntax-highlighting",
            dest: "{{ ansible_env.HOME }}/.zsh/zsh-syntax-highlighting",
          }

    # Install zoxide
    - name: Install zoxide
      ansible.builtin.shell:
        cmd: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
        executable: /bin/bash
      args:
        creates: "{{ ansible_env.HOME }}/.zoxide"

    # Install oh-my-posh
    - name: Install oh-my-posh
      ansible.builtin.shell:
        cmd: curl -s https://ohmyposh.dev/install.sh | bash -s
        executable: /bin/bash
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-posh"

    # Install fzf
    - name: Install fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ ansible_env.HOME }}/.fzf"
        update: yes

    - name: Run fzf installer
      command: "{{ ansible_env.HOME }}/.fzf/install --all"
      args:
        chdir: "{{ ansible_env.HOME }}/.fzf"

    # Install VSCode
    - name: Add Microsoft GPG key and VSCode repository
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VSCode repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present

    - name: Install VSCode
      apt:
        name: code
        state: present

    # Install JetBrains Mono Nerd Font
    - name: Download JetBrains Mono Nerd Font
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip"
        dest: "/tmp/JetBrainsMono.zip"

    - name: Ensure fonts directory exists
      file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory

    - name: Unzip JetBrains Mono Nerd Font
      unarchive:
        src: "/tmp/JetBrainsMono.zip"
        dest: "{{ ansible_env.HOME }}/.local/share/fonts/"
        remote_src: yes

    - name: Update font cache
      command: fc-cache -f -v

    # Install Ulauncher
    - name: Download Ulauncher DEB
      get_url:
        url: "https://github.com/Ulauncher/Ulauncher/releases/download/5.15.7/ulauncher_5.15.7_all.deb"
        dest: "/tmp/ulauncher.deb"

    - name: Install Ulauncher
      apt:
        deb: "/tmp/ulauncher.deb"

    # Install Ghostty
    - name: Download Ghostty DEB
      get_url:
        url: "https://github.com/mkasberg/ghostty-ubuntu/releases/download/1.0.1-0-ppa2/ghostty_1.0.1-0.ppa2_amd64_24.04.deb"
        dest: "/tmp/ghostty.deb"

    - name: Install Ghostty
      apt:
        deb: "/tmp/ghostty.deb"
